name: Generate profile summary cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: inwpu
          BRANCH_NAME: main         # 可省略，默认就是 main
          UTC_OFFSET: 8             # 你在东八区就写 8
          EXCLUDE: ""               # 需要排除的语言，逗号分隔；没有就留空
          AUTO_PUSH: true           # 生成后自动提交
